Task refactor units
vegastrike/Vega-Strike-Engine-Source pull request #330
Opened 2020-09-29 13:30 UTC by royfalk

Another PR that is part of #73. This one removes the generic unit subclasses (missile_generic.h for example) and aligns subclasses around the file name (class Missile).

Code Changes:
- [Yes ] Have the PR Validation Tests been run? 

Issues:
- Fixed a bug in the collision code. It seems an Asteroid unit is the entire field and actual asteroids are subunits. When colliding with one, I called the kill, which caused the entire field to disappear.

Purpose:
- What release is this for? 0.7 probably.
- Is there a project or milestone we should apply this to?

2020-09-29 14:06 UTC, BenjamenMeyer commented on engine/src/cmd/building.h
> +    virtual enum clsptr isUnit() const
we probably should rename the `clsptr` enum to be more descriptive

2020-09-29 14:08 UTC, BenjamenMeyer commented on engine/src/cmd/nebula.cpp
> +void Nebula::beginElem( const std::string &name, const AttributeList &atts )
this probably should also be called `beginElement()` and allow for function overloading to do the work.

2020-09-29 14:15 UTC, BenjamenMeyer reviewed
Overall I don't see anything in particularly wrong; left a couple comments on further refactoring - this PR or another. Let's get this play tested and it should be good to merge.

2020-09-29 19:02 UTC, evertvorster commented
Hi there! I have not fully tested this PR, but I am noticing something weird. 

Top speed with SPEC is only 10 x C, and not 100 x C that I am used to getting. 
I have noticed it on another of Roy's branches, too, but thought I was mistaken. It's only now that I have switched back and forth between master and this branch that I know for certain!

2020-10-04 17:40 UTC, stephengtuggy commented
Well, we'll certainly need to fix the SPEC top speed issue before merging this.

I will still try to review this PR in detail today or tomorrow.

2020-10-09 14:02 UTC, stephengtuggy requested changes
Mostly looks good. Just a couple of things I noticed.

2020-10-17 18:58 UTC, stephengtuggy commented on engine/src/cmd/nebula.h
> +        Nebula& operator=( const Nebula& );
@royfalk Update: It looks like the optimum syntax to use in C++11 is `= delete`. Any objections to using that form?

2020-10-18 00:36 UTC, stephengtuggy commented on engine/src/cmd/missile.cpp
> +//}
I guess this isn't used anywhere, or there would have been a compile error. So I suppose it's OK to leave out. I was just curious.

2020-10-22 03:15 UTC, stephengtuggy commented on engine/src/cmd/nebula.h
> +        Nebula& operator=( const Nebula& );
Roy, was `= delete` the syntax you wanted to use originally for forbidden constructors? 😆 If so, you were smarter than me or @BenjamenMeyer in this case. We weren't familiar with the C++11 syntax yet lol

2020-10-22 03:16 UTC, stephengtuggy commented on engine/src/cmd/nebula.h
> +        Nebula& operator=( const Nebula& );
And the more I think about it, the more I realize that this isn't really a blocker. If you want to merge master into this branch, we can probably go ahead and merge the PR. Any constructor cleanup can be done later.

2020-10-22 03:17 UTC, stephengtuggy approved these changes
After further consideration, this is fine for now. I think we can go ahead and merge it.

2020-10-22 12:23 UTC, stephengtuggy commented
It looks like the top speed 9C issue had made it into master already, before this PR. So I think this PR may be safe to merge. I'll just want to do a little play testing on it myself, to double check.

2020-10-23 06:28 UTC, stephengtuggy commented
After some play testing, this looks good to me. Top speed is back to 97C. 👍🏼 Merging.

2020-10-23 06:28 UTC, merged