Update version to 0.8.x
vegastrike/Vega-Strike-Engine-Source pull request #347
Opened 2020-11-28 05:33 UTC by BenjamenMeyer

- Updating the engine version to 0.8.x
- Adds basic support for #152
- How to change version info is documented at https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Changing-Vega-Strike-Engine-Version-Numbers

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [ ] This is a documentation change only

Issues:
- #152 

Purpose:
- What is this pull request trying to do? Update the version for the master branch
- What release is this for? 0.8.x
- Is there a project or milestone we should apply this to? 0.8.x

2020-11-28 07:08 UTC, evertvorster commented
Hmm.. what is this --version supposed to do?
I would have thought it would print out the version of the VegaStrike engine and then exit, but this is what I get at the console:
[evert@Vorster vegastrike-engine-git]$ vegastrike --version
[2020-11-28 09:05:13.682702] [0x00007f2608d2ac00] [trace]   Registering codec ogg
[2020-11-28 09:05:13.682731] [0x00007f2608d2ac00] [trace]   .

 In path /data/OS/aur/vegastrike-engine-git
Vega Strike  
See http://www.gnu.org/copyleft/gpl.html for license details.

ARG #1 = --version
Command line options for vegastrike

 -D -d   Specify data directory
 -N -n   Number of players
 -M -m   Specify a mod to play
 -P -p   Specify player location
 -J -j   Start in a specific system
 -A -a   Normal resolution (800x600)
 -H -h   High resolution (1024x768)
 -V -v   Super high resolution (1280x1024)
 --net   Networking Enabled (Experimental)
 --debug[=#]     Enable debugging output, 1 major warnings, 2 medium, 3 developer notes
 --test-audio    Run audio tests
 --version       Print the version and exit

[evert@Vorster vegastrike-engine-git]$

2020-11-28 20:02 UTC, BenjamenMeyer commented
Thanks. I'll look closer. It should work line '--help'.

2020-11-28 21:39 UTC, BenjamenMeyer commented
Found my linker issue...must have been a while since I did a master build as I was missing libgtk-3-dev (Ubuntu); fixed that and it built right up. Verified that `--version` actually does print the version now (sorry about that dumb bug).

2020-11-28 21:40 UTC, BenjamenMeyer commented
I'll try to play test later on.

2020-11-29 18:02 UTC, stephengtuggy requested changes
Can we leave out the `TWEAK` version number? Thanks. Also, there are more places that will need to change; see my additions to https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Changing-Vega-Strike-Engine-Version-Numbers .

2020-11-29 18:02 UTC, stephengtuggy commented on engine/src/main.cpp
> +                    exit( 0 );
Cool; looks like this will work now.

2020-11-29 22:02 UTC, BenjamenMeyer commented
@stephengtuggy I was thinking of using the Tweak part for the git hash at some point. We don't need it in the packaging, but printing it in --version would be useful.

2020-11-29 22:40 UTC, stephengtuggy commented
> @stephengtuggy I was thinking of using the Tweak part for the git hash at some point. We don't need it in the packaging, but printing it in --version would be useful.

@BenjamenMeyer Yeah, now that you mention it, I can see the usefulness of doing that. Perhaps we can put the git hash after a plus sign, as in https://semver.org/#spec-item-10 .

2020-11-30 14:13 UTC, evertvorster approved these changes
It works as advertised now. 
All good in my book!

2020-12-01 05:32 UTC, BenjamenMeyer commented on engine/CMakeLists.txt
> +SET(VEGASTRIKE_VERSION_TWEAK "0")
As noted below in (https://github.com/vegastrike/Vega-Strike-Engine-Source/pull/347#issuecomment-735465038) I'd like to use that for the Git Hash.

CPack makes no mention of using Tweak; so it should only show up in the code once we automate things. We can format however, if we want to do x.y.z+h that's fine.

2020-12-01 05:57 UTC, BenjamenMeyer commented on engine/CMakeLists.txt
> +SET(VEGASTRIKE_VERSION_TWEAK "0")
Added a line of documentation about the intent for that field.

2020-12-03 02:20 UTC, stephengtuggy approved these changes
Looks good to me!

2020-12-03 02:20 UTC, stephengtuggy commented on engine/CMakeLists.txt
> +SET(VEGASTRIKE_VERSION_TWEAK "0")
@BenjamenMeyer Cool. Looks good.

2020-12-03 02:20 UTC, stephengtuggy commented on engine/src/main.cpp
> +    "Vega Strike Engine Version 0.8.0+0\n"
Nice 👍🏼

2020-12-03 15:10 UTC, merged