Remove TemplateManager and VSFileXMLSerializer
vegastrike/Vega-Strike-Engine-Source pull request #421
Opened 2021-02-09 16:55 UTC by royfalk

Purpose:
- What is this pull request trying to do? Remove older code. In this case, my target was VSFileXMLSerializer. 
- What release is this for? The coming one.
- Is there a project or milestone we should apply this to? @BenjamenMeyer 

Template Manager is part of the audio and does not appear to be used at the moment, but it's relatively clean and modern code. Audio works fine without it. I wonder if it was a replacement to current code.
I also had to gut the test file.

Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- One jump had a rendering freeze for 2-3 seconds. Following jump was fine.

2021-02-09 17:54 UTC, Loki1950 approved these changes
Not sure about the audio potion IIRC kluass's was trying to modernism the audio

2021-02-11 04:26 UTC, BenjamenMeyer commented
NOTE: Seems the builds that failed had an issue with Py3 and Boost-Python. Not sure why but that's the build error.

2021-02-12 02:07 UTC, stephengtuggy commented
I will try to review this PR this weekend. Can we get the builds passing before then?

2021-02-12 03:29 UTC, BenjamenMeyer requested changes
Blocking until builds pass.

2021-02-13 21:50 UTC, stephengtuggy requested changes
The Boost_Python changes here are probably what is breaking the build.

Apart from that, I'm worried that the positional audio functionality will no longer work. It works for me at present; does it not work for you guys?

Is there some other code elsewhere that takes care of positional audio, that I'm just not seeing?

2021-02-13 21:50 UTC, stephengtuggy commented on engine/CMakeLists.txt
> +            SET(BOOST_PYTHON_COMPONENT "python38")
Why tie Boost-Python to a particular Python version, on a particular set of platforms/variants? Please revert this, or find another way to do it. These `python38` changes are probably why the build is breaking.

2021-02-21 15:53 UTC, royfalk commented
Sorry. For some reason I got a whole bunch of emails about changes to the packages and none for this PR.
As I noted, this code is not actually used yet.
Now that I've noticed it, I'll try and get to it today or tomorrow.

2021-02-23 11:03 UTC, royfalk commented
OK. So build passes but CodeQL is complaining about code I didn't touch. 
I fixed the CMakeList file, so I think we're good to go.

2021-02-24 04:17 UTC, stephengtuggy approved these changes
OK. Looks fine to me at this point.

2021-02-26 15:08 UTC, BenjamenMeyer approved these changes

2021-02-26 15:08 UTC, merged