Additional refactoring to bolt class
vegastrike/Vega-Strike-Engine-Source pull request #434
Opened 2021-03-17 18:12 UTC by royfalk

Purpose:
- What is this pull request trying to do? Refactor bolt classes. Merge bolt_generic into bolt. etc.
- What release is this for? Next one.
- Is there a project or milestone we should apply this to? Not really.

Please answer the following:

Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues:
- Intermittent jump freeze for several seconds (visual only). This was already seen in previous commits.

2021-03-18 03:02 UTC, BenjamenMeyer requested changes
a few code style changes and it should be good - it's part of updating/migrating code and should help fix bugs too.

2021-03-18 03:02 UTC, BenjamenMeyer commented on engine/src/gfx/boltdrawmanager.cpp
> +            bolts[i][j].Destroy( j );
please add braces around these

2021-03-18 13:50 UTC, evertvorster commented
I've given it a good play test, and everything seems to work fine, with no new issues. I play-tested with the Llama, accepted missions, and even shot at Oswald a little. 

Then I tested with the Vendetta, and I got a little carried away, and jumped from the edge of my exploratory efforts to Sol/Sol over about 20 jumps. Sol/Sol did not load on my system, and crashed the game. Of course, I have not saved my game all the way in, which is a little annoying.

2021-03-18 13:52 UTC, evertvorster approved these changes
No new issues to report. Looks good to me!

2021-03-29 13:55 UTC, BenjamenMeyer approved these changes
Thanks!

2021-03-29 13:56 UTC, BenjamenMeyer commented
given the last commit is only whitespace changing for code style it's good for merge

2021-03-30 04:48 UTC, merged