Bug Fix: Document the helper scripts
vegastrike/Vega-Strike-Engine-Source pull request #440
Opened 2021-04-06 03:27 UTC by BenjamenMeyer

Add some documentation about the helper scripts

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [x] This is a documentation change only

Issues:
- https://github.com/vegastrike/Assets-Masters/issues/23

Purpose:
Document the helper scripts that @evertvorster created.

2021-04-06 17:28 UTC, Loki1950 approved these changes

2021-04-07 01:37 UTC, stephengtuggy commented
So I'm not actually sure that the `vsettings` script or icon has made it into the assets beta yet. I think they may have been committed on master only. Let's make sure that that is rectified, otherwise we will be documenting a script that doesn't exist.

2021-04-07 03:55 UTC, stephengtuggy requested changes
One minor change to request. Otherwise, looks good.

2021-04-07 03:55 UTC, stephengtuggy commented on README.md
> +Starting with 0.7.x there are some helper scripts for running Vega Strike and it's configuration utility:
`its` not `it's`

2021-04-07 04:16 UTC, BenjamenMeyer commented
I checked the 0.7.x Beta 3 Deb file and can confirm the scripts are in there.

2021-04-07 04:17 UTC, BenjamenMeyer commented on README.md
> +Starting with 0.7.x there are some helper scripts for running Vega Strike and it's configuration utility:
fixed in latest commit

2021-04-07 13:15 UTC, stephengtuggy approved these changes
Looks good to me!

2021-04-07 13:16 UTC, merged