Minor refactoring of weapons (beam/bolt)
vegastrike/Vega-Strike-Engine-Source pull request #561
Opened 2021-09-26 13:48 UTC by royfalk

This PR is part of an ongoing refactoring of the code base. It is for the next release.

Please answer the following:

Code Changes:
- [Yes] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation

Issues: None due to this PR. I will be opening multiple bugs later.

2021-09-26 16:43 UTC, stephengtuggy requested changes
This code seems functional enough, and it definitely fixes the "invisible beam" problem. However, I think we need to address the 4 "Multiplication result converted to larger type" issues before we merge this.

2021-09-27 06:09 UTC, royfalk commented
> This code seems functional enough, and it definitely fixes the "invisible beam" problem. However, I think we need to address the 4 "Multiplication result converted to larger type" issues before we merge this.

I usually don't mind doing some minor edits of nearby code, but this ain't it. I moved these functions from beam_generic to beam without touching them at all. You can tell there are 4 "fixed" warnings in beam_generic.

It's tempting to cast each part of the expression to double just to get rid of the warning but I vote against. This is a part of the code I don't understand at all and the original developers had a fondness for pushing the envelope in terms of what can be done. My concern here is someone originally said "let's do this by having it overflow in float" and fixing it would introduce some subtle or not so subtle bug.

I am fine with a new issue to deal with this, assigned to me. I'll get to it this week and test it separately.  I'll also try and understand the code a little and maybe polish some of it.

2021-09-27 13:34 UTC, stephengtuggy approved these changes
OK, fair enough. Approving.

2021-09-27 19:19 UTC, BenjamenMeyer approved these changes

2021-09-27 19:30 UTC, merged