Enhancement: Asset API change log documentation
vegastrike/Vega-Strike-Engine-Source pull request #617
Opened 2021-12-07 05:57 UTC by BenjamenMeyer

Introduction of the Asset API change log documentation.

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
- [x] This is a documentation change only

Issues:
- #349

Purpose:
Add a change log for the Asset API so game asset devs can easily determine which version they need to check for.

2021-12-07 16:41 UTC, P-D-E commented on doc/ASSET_API.rst
> +For simplicity, the Asset API Version is a simple incrementing interger value with a behavior
interger -> integer

2021-12-07 16:43 UTC, P-D-E commented on doc/ASSET_API.rst
> +determining available functionality.
for the determining available functionality:
Did you mean 'for determining the available functionality' ?

2021-12-09 14:02 UTC, stephengtuggy requested changes
I have a few editorial changes to suggest. Other than that, it looks good. Glad we have this document now.

2021-12-09 14:02 UTC, stephengtuggy commented on doc/ASSET_API.rst
> +Essentially, any time a change happens to the Asset API that may effect the Game Assets.
effect -> affect (in this case)

2021-12-10 04:24 UTC, Loki1950 approved these changes

2021-12-23 16:49 UTC, Loki1950 approved these changes

2021-12-23 17:41 UTC, P-D-E approved these changes

2021-12-25 01:21 UTC, stephengtuggy approved these changes
LGTM!

2021-12-25 01:25 UTC, merged