peg boost to 1.77, 1.78 currently causes compilation issues
vegastrike/Vega-Strike-Engine-Source pull request #649
Opened 2022-02-09 22:45 UTC by v98sbftt07

Thank you for submitting a pull request and becoming a contributor to the Vega Strike Core Engine.

Please answer the following:

Code Changes:
- [ ] Have the PR Validation Tests been run? See https://github.com/vegastrike/Vega-Strike-Engine-Source/wiki/Pull-Request-Validation
  Only completed a build test.
- [ ] This is a documentation change only

Issues:
- Please list any related issues

Purpose:
The Windows build seems broken currently.  This pull request downgrades Boost as that seems to repair the build.  The problem with .78 may be related to https://github.com/microsoft/vcpkg/issues/22495 

Not sure if there is a better way to fix this while keeping 1.78 in use...

2022-02-10 02:35 UTC, BenjamenMeyer approved these changes
LGTM, @stephengtuggy for final review before merge (assuming CI passed)

2022-02-16 15:01 UTC, stephengtuggy commented
This may be relevant: https://vcpkg.io/en/docs/examples/modify-baseline-to-pin-old-boost.html

2022-02-17 00:27 UTC, stephengtuggy requested changes
Blocking until Windows CI passes

2022-02-19 22:32 UTC, stephengtuggy commented
#650 just got merged, so it's possible that this PR is no longer needed. Would want to review before closing it though.

2022-05-05 23:16 UTC, stephengtuggy commented
Superseded by #650

2022-05-05 23:16 UTC, closed without merging